ansible/jinja-docsite

CONTRIBUTING.md
Need to be clear this is not the current docsite repo and than any proposals here may not land in the final docsite if we decide to use an off-the-shelf site generator instead.
=> make it obvious this is a prototype site

data/base.yaml, data/links.yaml, data/pages.yaml, templates/index.html
This PR fixes #9 improves the yaml for the index page based on persona journeys.
=> Update index page links based on journeys

data/links.yaml, data/pages.yaml, sass/main.scss, templates/developer.html
Fixes #16 by adding developer content based on user journeys
=> Developer content

data/links.yaml, data/pages.yaml, templates/developer.html, templates/index.html
This PR creates a novice journey section under pages and reduces the number of button group labels.
=> Simplify pages yaml

data/links.yaml, data/pages.yaml, templates/index.html, templates/maintainer.html
Fixes #18 by adding content for community maintainer journeys
=> Add maintainer journeys

data/links.yaml, data/pages.yaml, templates/index.html, templates/user.html
Fixes #17 by adding content for user persona journeys
=> Add user journeys

sass/_button.scss, sass/_cards.scss, sass/_clipboard.scss, sass/main.scss, templates/developer.html, templates/ecosystem.html, templates/index.html, templates/maintainer.html, templates/user.html
=> Revert colors to black and white

templates/index.html
=> Removes pip install clipboard from main docs landing page

data/links.yaml, data/pages.yaml, sass/main.scss, templates/_nav.html, templates/automation.html, templates/platform.html
=> Port over aap content

data/links.yaml, data/projects.yaml, templates/ecosystem.html
=> Add collections to ecosystem

data/links.yaml, data/pages.yaml, templates/community.html
=> Update the community page

data/links.yaml, data/pages.yaml, templates/404.html, templates/_nav.html, templates/automation.html, templates/blog.html, templates/collections.html, templates/community.html, templates/core.html, templates/index.html
=> Add stubs for core and collections

templates/_footer.html
Fixes #67 
I don't think we need code licensing so CC by SA 4.0 is good.
=> Use cc by sa 4.0 license

sass/_nav.scss, sass/main.scss, templates/_nav.html, templates/_scripts.html
Fixes  #31
The other part of the prototype docsite that needs more responsiveness is the nav bar.
=> Responsive nav

sass/main.scss, sass/redhat-footer.scss
=> Use normal font weight throughout

data/pages.yaml, data/projects.yaml
Partly solves https://github.com/ansible/jinja-docsite/issues/69
Note: i added "Ansible" to AWX in attempt to move it to somewhere at the beginning
=> Ansible core, Ansible ecosystem: misc changes

sass/_docbar.scss, sass/_nav.scss, sass/main.scss, templates/_base.html, templates/_docbar.html, templates/_nav.html
=> Use the ansible.com nav bar

data/pages.yaml
Relates to https://github.com/ansible/jinja-docsite/issues/66
As in the issue ^
- `Ansible offers powerful and flexible automation that is simple, decentralized, and easy.`: the words `simple` and `easy` feel a bit like a repetition of the same thing, i'm not a native speaker though. Maybe `simple, decentralized, and free`?
- Also the meaning of `decentralized` is not obvious for me in this context. If you have a controller, you have kinda center:) Should we maybe replace it with something `simple, ???, and free` ?
I suggest improving it a bit
=> Change Ansible description

data/links.yaml, data/pages.yaml, templates/developer.html
Relates to https://github.com/ansible/jinja-docsite/issues/71
Didn't find how to change the items in the list on the landing page
=> Developers content: change

data/pages.yaml, templates/index.html
@Andersson007 I think we broke a link with https://github.com/ansible/jinja-docsite/commit/f76c7f71ea960263e1ec3e76c07a0bb5b8af8cab
=> fix broken developer link

data/links.yaml, data/pages.yaml, templates/community.html
Fixes https://github.com/ansible/jinja-docsite/issues/68
=> Join the community: alternative layout

data/links.yaml, data/pages.yaml, templates/index.html, templates/maintainer.html
Fixes https://github.com/ansible/jinja-docsite/issues/72
=> Maintainer: improve

sass/_grid.scss
Fixes the mobile issue (somehow)
=> rm 3em space to fix mobile issue

data/links.yaml, data/projects.yaml, templates/ecosystem.html
Fixes https://github.com/ansible/docsite/issues/141
=> Add edge to the ecosystem

templates/ecosystem.html
Fixes https://github.com/ansible/docsite/issues/160
=> Alphabetize ecosystem

data/links.yaml, data/pages.yaml, templates/automation-tower-chinese-translations.html, templates/automation-tower-japanese-translations.html, templates/automation-tower-korean-translations.html, templates/automation-tower-prior-versions.html
Update the translation pages for 4.2.2.
This PR updates the source files that generate HTML for the docsite and relates to https://github.com/ansible/docsite/pull/167
=> Edit source files for Tower translations 4.2.2

oldsite/automation-tower-chinese-translations.html, oldsite/automation-tower-japanese-translations.html, oldsite/automation-tower-korean-translations.html, oldsite/automation-tower-prior-versions.html
Fixes https://github.com/ansible/docsite/issues/168
=> Add 4.2.2 to the controller oldsite prior versions

data/ecosystem.yaml
Make sure all RTD links point to subprojects.
=> Update ecosystem links
